networks:
    laravel_network:
        name: laravel_network

services:
    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        container_name: nginx
        ports:
            - 4000:80
            - 443:443
        volumes:
            - .:/var/www/html:delegated
        networks:
            - laravel_network
        depends_on:
            - php
            - mysql
            - phpmyadmin
    php:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: php
        volumes:
            - .:/var/www/html:delegated
        networks:
            - laravel_network

    mysql:
        image: mysql:8
        environment:
            MYSQL_DATABASE: laravel_11_api
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        container_name: mysql
        ports:
            - 4306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - laravel_network

    # afin de lancer les commandes artisan sous docker je crée un service(container) artisan
    artisan:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: artisan
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        entrypoint: ["php", "artisan"]
        networks:
            - laravel_network

    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel_network

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        ports:
            - 2023:80
        environment:
            PMA_HOST: mysql
            PMA_USER: homestead
            PMA_PASSWORD: secret
        networks:
            - laravel_network
